name: do_listing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-1804_listing:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu package)
      run: sudo apt install python3-numpy
    - name: create listing
      run: env python3 list_numpy_dtypes.py
    - name: creating json output
      run: env python3 list_numpy_dtypes_json.py
    - name: upload json instance as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-1804_listing
        path: data.json

  ubuntu-2004_listing:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu package)
      run: sudo apt install python3-numpy
    - name: create listing
      run: env python3 list_numpy_dtypes.py
    - name: creating json output
      run: env python3 list_numpy_dtypes_json.py
    - name: upload json instance as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-2004_listing
        path: data.json

  macos-1015_listing:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies via pip3
      run: pip3 install numpy
    - name: create listing
      run: env python3 list_numpy_dtypes.py
    - name: creating json output
      run: env python3 list_numpy_dtypes_json.py
    - name: upload json instance as artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-1015_listing
        path: data.json

  macos-11_listing:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    if: ${{ false }}
    # https://github.com/actions/virtual-environments/issues/2486
    # https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies via pip3
      run: pip3 install numpy
    - name: create listing
      run: env python3 list_numpy_dtypes.py
    - name: creating json output
      run: env python3 list_numpy_dtypes_json.py
    - name: upload json instance as artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-11_listing
        path: data.json

  windows-2016_listing:
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2016-Readme.md
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
    - name: conda init powershell
      run: |
        &($env:CONDA + "\Scripts\conda") init powershell
    - name: install dependencies via conda
      run: conda install -c conda-forge numpy
    - name: create listing
      run: python list_numpy_dtypes.py
    - name: creating json output
      run: python list_numpy_dtypes_json.py
    - name: upload json instance as artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-2016_listing
        path: data.json

  windows-2019_listing:
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: conda init powershell
      run: |
        &($env:CONDA + "\Scripts\conda") init powershell
    - name: install dependencies via conda
      run: conda install -c conda-forge numpy
    - name: create listing
      run: python list_numpy_dtypes.py
    - name: creating json output
      run: python list_numpy_dtypes_json.py
    - name: upload json instance as artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-2019_listing
        path: data.json

  combine:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
    runs-on: ubuntu-latest
    needs: [ubuntu-1804_listing, ubuntu-2004_listing, macos-1015_listing, windows-2016_listing, windows-2019_listing]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - name: combine results
      run: env python3 combine_results.py
    - name: generate output
      run: |
        mkdir results
        mv index.html results/
    - name: adapt doc fo jekyll
      if: ${{ github.event_name == 'push' }}
      run: touch results/.nojekyll
    - name: deploy pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: results
        folder: results
